export const MoviesList =[
    {id : 1, name : "Inviseble Guest", img : "/invisGuest.jpg", rate: 5, overview :"A successful young businessman is accused of murdering his girlfriend. He hires a top-rate lawyer to defend him. She senses that he is not providing the full picture and questions him on the background to the murder, in particular an incident that occurred to the two of them a few months earlier.", video :"https://www.youtube.com/watch?v=epCg2RbyF80" },
    {id :2, name : "Ice-Age", img : "/ice-age.jpg", rate: 4, overview :"a strange animal unexpectedly triggers a new glaciation. As the distraught animals flee the icy winds, Manny, a lone mammoth, goes against the tide. He is soon flanked by a companion, Sid the lazy, who imposed his talkative presence on him. Along the way, the two friends encounter a human tribe decimated by the ruthless saber-toothed tigers.", video :"https://www.youtube.com/watch?v=0vPHYRJtLYE"},
    {id : 3, name:"Mirage", img :"/Mirage.jpg", rate: 2, overview :"Vera Roy, une femme heureuse en ménage, voit sa vie devenir un cauchemar lorsqu'elle essaie d'éviter un crime qui entraîne une série de réactions en chaîne.", video : "https://www.youtube.com/watch?v=3NCOwTBWYdE&t=2s"},
    {id:4, name :"Interstellar", img :"/interstellar.jpg", rate: 5, overview:"Dans un proche futur, la Terre est devenue hostile pour l'homme. Les tempêtes de sable sont fréquentes et il n'y a plus que le maïs qui peut être cultivé, en raison d'un sol trop aride. Cooper est un pilote, recyclé en agriculteur, qui vit avec son fils et sa fille dans la ferme familiale. Lorsqu'une force qu'il ne peut expliquer lui indique les coordonnées d'une division secrète de la NASA, il est alors embarqué dans une expédition pour sauver l'humanité.", video: "https://www.youtube.com/watch?v=zSWdZVtXT7E"},
    {id:5, name: "Inception", img: "/inception.jpg", rate : 3, overview:"Dom Cobb est un voleur expérimenté dans l'art périlleux de `l'extraction' : sa spécialité consiste à s'approprier les secrets les plus précieux d'un individu, enfouis au plus profond de son subconscient, pendant qu'il rêve et que son esprit est particulièrement vulnérable. Très recherché pour ses talents dans l'univers trouble de l'espionnage industriel, Cobb est aussi devenu un fugitif traqué dans le monde entier. Cependant, une ultime mission pourrait lui permettre de retrouver sa vie d'avant.",video :"https://www.youtube.com/watch?v=YoHD9XEInc0&t=58s"},
    {id:6 ,name : "Sutter-Island", img :"/shutter-island.jpg", rate:4, overview :"En 1954, une meurtrière, extrêmement dangereuse, placée en centre de détention psychiatrique disparaît sur l'île de Shutter Island. Deux officiers du corps fédéral des marshals, Teddy Daniels et Chuck Aule, sont envoyés sur place pour enquêter. Très vite, Teddy Daniels comprend que le personnel de l'établissement cache quelque chose. Seul indice dont il dispose : un bout de papier sur lequel est griffonnée une suite de chiffres entrecoupée de lettres.", video :"https://www.youtube.com/watch?v=5iaYLCiq5RM"},
    {id : 8, name : "Tag", img :"/tag.jpg", rate: 3, overview: "Cinq potes à l'esprit de compétition très aiguisé se lancent dans une partie de chat perché où tous les coups sont permis. Une tradition qui dure depuis l'école primaire où les cinq lascars mettent en jeu leur boulot, leurs relations et leur propre vie. Cette année, la partie se déroule au moment où le seul joueur qui n'a encore jamais perdu se marie. Autant dire qu'il devrait être une proie facile.", video : "https://www.youtube.com/watch?v=AZGcmvrTX9M"},
    {id:7 ,name : "Tenet", img :"/tenet.jpg", rate:4, overview :"Muni d'un seul mot, et décidé à se battre pour sauver le monde, un homme sillonne l'univers crépusculaire de l'espionnage international. Sa mission le projettera dans une dimension qui dépasse le temps. Pourtant, il ne s'agit pas d'un voyage dans le temps, mais d'un renversement temporel.",video :"https://www.youtube.com/watch?v=kjC1zmZo30U"},
     {id :10, name : "Us", img :"/us.jpg", rate: 3, overview : "Les vacances s'annoncent reposantes pour Adelaide et Gabe Wilson et leurs deux enfants. À peine les valises posées dans la maison au bord d'un lac qu'Adelaide, cédant à la pression, accepte à contrecoeur d'aller passer la journée à la plage de Santa Cruz. La famille y rejoint des amis, les Tyler, mais Adelaide est troublée par le souvenir d'un évènement qu'elle y a vécu dans son enfance. De retour chez eux, les Wilson sont attaqués par quatre inconnus qui leur ressemblent étrangement.", video: "https://www.youtube.com/watch?v=hNCmb-4oXJA"},
     {id :11, name :"Zootopia", img :"/zotopia.jpg", rate : 2, overview :"Zootopia est une ville qui ne ressemble à aucune autre : seuls les animaux y habitent ! On y trouve des quartiers résidentiels élégants comme le très chic Sahara Square, et d'autres moins hospitaliers comme le glacial Tundratown. Dans cette incroyable métropole, chaque espèce animale cohabite avec les autres. Qu'on soit un immense éléphant ou une minuscule souris, tout le monde a sa place à Zootopia ", video :"https://www.youtube.com/watch?v=jWM0ct-OLsM" }
   ]